import test from "node:test";
import assert from "node:assert/strict";
import { ENTITIES, LOCATIONS, WORLD, buildFlashcards, canInvokeWaterGift, createJournal, grantItem, recordEncounter, resolveWaterGift, setConfirmed, setGuess } from "../src/lessons.js";
import { PLAYER_SPEED, SOUTH_GATE_DETAIL, isPlayerWalkable, isWorldWalkable, projectWorldPoint } from "../src/game.js";

test("encounters accumulate without revealing a canonical answer", () => { let journal = createJournal(); journal = recordEncounter(journal, "水", "長街", "well", 1); journal = recordEncounter(journal, "水", "茶坊", "disciple", 2); assert.equal(journal.entries.water.count, 2); assert.equal(journal.entries.water.lastLocation, "茶坊"); assert.deepEqual(journal.entries.water.locations, ["長街", "茶坊"]); assert.equal("answer" in journal.entries.water, false); });
test("player guesses remain editable and confirmation is self-directed", () => { let journal = recordEncounter(createJournal(), "茶", "茶坊", "tea-pot", 1); journal = setGuess(journal, "tea", "  tea / a drink  "); journal = setConfirmed(journal, "tea", true); assert.equal(journal.entries.tea.guess, "tea / a drink"); assert.equal(journal.entries.tea.confirmed, true); });
test("only player-confirmed guesses become flashcards", () => { let journal = recordEncounter(createJournal(), "茶", "茶坊", "tea-pot", 1); journal = recordEncounter(journal, "水", "長街", "well", 2); journal = setGuess(journal, "tea", "tea"); journal = setConfirmed(journal, "tea", true); journal = setGuess(journal, "water", "water"); assert.deepEqual(buildFlashcards(journal).map(card => card.id), ["tea"]); });
test("the contextual event requires the observed words and the world item", () => { let journal = createJournal(); journal = recordEncounter(journal, "給", "長街", "water-carrier", 1); journal = recordEncounter(journal, "水", "長街", "well", 2); assert.equal(canInvokeWaterGift(journal, ["give", "water"]), false); journal = grantItem(journal, "water-flask"); assert.equal(canInvokeWaterGift(journal, ["water"]), false); assert.equal(canInvokeWaterGift(journal, ["give", "water"]), true); assert.equal(resolveWaterGift(journal, ["give", "water"]).quest, "resolved"); });
test("the follow-camera map keeps every district and interaction reachable", () => { assert.ok(WORLD.width > 1600 && WORLD.height > 900); for (const location of LOCATIONS) { const [left, top, right, bottom] = location.bounds; assert.ok(left >= 0 && top >= 0 && right <= WORLD.width && bottom <= WORLD.height); } for (const entity of ENTITIES) { assert.ok(entity.x >= 0 && entity.x <= WORLD.width && entity.y >= 0 && entity.y <= WORLD.height, entity.id); assert.ok(isWorldWalkable(entity.x, entity.y), `${entity.id} is outside the connected paths`); } });
test("the close exploration camera reveals only a local part of town at a stable scale", () => { const camera = { focusX: 1200, focusY: 800, zoom: 1.5 }; const far = projectWorldPoint(1200, 400, camera); const focus = projectWorldPoint(1200, 800, camera); const near = projectWorldPoint(1200, 1200, camera); assert.equal(focus.x, 800); assert.equal(far.scale, focus.scale); assert.equal(near.scale, focus.scale); assert.ok(Math.abs((near.y - focus.y) - (focus.y - far.y)) < 1e-9); assert.ok(1600 / camera.zoom < WORLD.width / 2); assert.ok(900 / camera.zoom < WORLD.height / 2); });
test("the high-detail South Gate plate covers the opening interactions at native display density", () => { const inside = entity => entity.x >= SOUTH_GATE_DETAIL.x && entity.x <= SOUTH_GATE_DETAIL.x + SOUTH_GATE_DETAIL.width && entity.y >= SOUTH_GATE_DETAIL.y && entity.y <= SOUTH_GATE_DETAIL.y + SOUTH_GATE_DETAIL.height; assert.ok(inside(ENTITIES.find(entity => entity.id === "gate-sign"))); assert.ok(inside(ENTITIES.find(entity => entity.id === "gatekeeper"))); assert.ok(Math.abs(SOUTH_GATE_DETAIL.width * 1.5 - 1672) < 2); assert.ok(Math.abs(SOUTH_GATE_DETAIL.height * 1.5 - 941) < 2); });
test("the South Gate walls block the player while the central doorway stays open", () => { assert.equal(isPlayerWalkable(1010, 1200), false); assert.equal(isPlayerWalkable(1390, 1200), false); assert.equal(isPlayerWalkable(850, 1400), false); for (let y = 1020; y <= 1530; y += 10) assert.equal(isPlayerWalkable(1200, y), true, `central route blocked at y=${y}`); });
test("walking speed is tuned for close, deliberate exploration", () => { assert.ok(PLAYER_SPEED.x <= 170); assert.ok(PLAYER_SPEED.y <= 155); assert.ok(PLAYER_SPEED.x * 1.5 <= 255); });
