import test from "node:test";
import assert from "node:assert/strict";
import { ENTITIES, LOCATIONS, WORLD, buildFlashcards, canInvokeWaterGift, createJournal, grantItem, recordEncounter, resolveWaterGift, setConfirmed, setGuess } from "../src/lessons.js";
import { isWorldWalkable } from "../src/game.js";

test("encounters accumulate without revealing a canonical answer", () => { let journal = createJournal(); journal = recordEncounter(journal, "水", "長街", "well", 1); journal = recordEncounter(journal, "水", "茶坊", "disciple", 2); assert.equal(journal.entries.water.count, 2); assert.equal(journal.entries.water.lastLocation, "茶坊"); assert.deepEqual(journal.entries.water.locations, ["長街", "茶坊"]); assert.equal("answer" in journal.entries.water, false); });
test("player guesses remain editable and confirmation is self-directed", () => { let journal = recordEncounter(createJournal(), "茶", "茶坊", "tea-pot", 1); journal = setGuess(journal, "tea", "  tea / a drink  "); journal = setConfirmed(journal, "tea", true); assert.equal(journal.entries.tea.guess, "tea / a drink"); assert.equal(journal.entries.tea.confirmed, true); });
test("only player-confirmed guesses become flashcards", () => { let journal = recordEncounter(createJournal(), "茶", "茶坊", "tea-pot", 1); journal = recordEncounter(journal, "水", "長街", "well", 2); journal = setGuess(journal, "tea", "tea"); journal = setConfirmed(journal, "tea", true); journal = setGuess(journal, "water", "water"); assert.deepEqual(buildFlashcards(journal).map(card => card.id), ["tea"]); });
test("the contextual event requires the observed words and the world item", () => { let journal = createJournal(); journal = recordEncounter(journal, "給", "長街", "water-carrier", 1); journal = recordEncounter(journal, "水", "長街", "well", 2); assert.equal(canInvokeWaterGift(journal, ["give", "water"]), false); journal = grantItem(journal, "water-flask"); assert.equal(canInvokeWaterGift(journal, ["water"]), false); assert.equal(canInvokeWaterGift(journal, ["give", "water"]), true); assert.equal(resolveWaterGift(journal, ["give", "water"]).quest, "resolved"); });
test("the follow-camera map keeps every district and interaction reachable", () => { assert.ok(WORLD.width > 1600 && WORLD.height > 900); for (const location of LOCATIONS) { const [left, top, right, bottom] = location.bounds; assert.ok(left >= 0 && top >= 0 && right <= WORLD.width && bottom <= WORLD.height); } for (const entity of ENTITIES) { assert.ok(entity.x >= 0 && entity.x <= WORLD.width && entity.y >= 0 && entity.y <= WORLD.height, entity.id); assert.ok(isWorldWalkable(entity.x, entity.y), `${entity.id} is outside the connected paths`); } });
